name: base
channels:
  - conda-forge
  - pyviz
  dependencies:
    - dask-jobqueue
    - mpi4py
    - pytest
    - pytest-runner
    - future
    - line_profiler
    - jupyterlab
    - jupyter
    - numpydoc
    - black
  # widgetsnbextension for the tqdm progressbar
  # for jupyterlab and extentions
    - nodejs
