name: base
channels:
  - conda-forge
  - pyviz
  dependencies:
    - nb_conda_kernels
    # every computing env should have ipykernel installed
    - jupyter
    - jupyterlab
    - line_profiler
    - numpydoc
    - black
  # widgetsnbextension for the tqdm progressbar
  # for jupyterlab and extentions
    - nodejs
    # Personal workflow stuff
    - cookiecutter

        # - dask-jobqueue
        # - mpi4py
        # - pytest
        # - pytest-runner
        # - future
